name: storm
version: 0.0.0

category: Game
description: Storm parses and generates Fortnite replays.
extra-source-files: README.markdown
github: tfausak/storm
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Fortnite replays.

dependencies:
  aeson-pretty: '>= 0.8.7 && < 0.9'
  aeson: '>= 1.3.1 && < 1.4'
  base: '>= 4.11.1 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  filepath: '>= 1.4.2 && < 1.5'
  text: '>= 1.2.3 && < 1.3'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies: storm
  ghc-options:
    - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables
